todolist/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root :to =>"home#index"
resources :tasks do
get 'mark'
end

end

todolist/app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :user

 validates :name, :status, :presence => true
 validates :name, :uniqueness => true

end

todolist/app/models/user.rb
class User < ActiveRecord::Base
 has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

todolist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?
 
protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:account_update) << :name
end
end

todolist/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      if user_signed_in?
          redirect_to :controller => 'tasks', :action => 'index'
       end
  end
end

todolist/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 def index
    @task = Task.where(user_id: current_user.id)
 end
  def show
     @task = Task.find(params[:id])
  end
  
  def  new
     @task = Task.new
  end

  def  create
      @task = Task.new(params[:task].permit(:name,:status))
      @task.user = current_user
     if @task.save
        redirect_to tasks_path, :notice => "your task has been saved"
     else
         render "new"
     end

  end

  def  edit
     @task = Task.find(params[:id])
  end

  def  update
      @task = Task.find(params[:id])
      
       if @task.update_attributes(params[:task].permit(:name,:status))
        redirect_to tasks_path, :notice => "your task has been updated"
       else
        render "edit"
       end
    
  end
 
  def mark
       @task = Task.find(params[:task_id])
       @task.update(:status => "Completed")
       redirect_to tasks_path, :notice => "your task has been marked as completed"     
  end

  def  destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path, :notice => "Task has been deleted"
  end
end

todolist/app/helpers/application_helper.rb
module ApplicationHelper
end

todolist/app/helpers/tasks_helper.rb
module TasksHelper
end

todolist/app/views/home/index.html.erb
<h1>Welcome to Todo</h1>

todolist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
   You are currently signed in as <%= current_user.email %>,not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
   <%= link_to "Sign up!", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
<% end %>

<% flash.each do |key,value| %>
<p><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

todolist/app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
       <h2> Errors:</h2>
   <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %>
       <% end %>
   </ul>
<% end %>
 <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
 </p>
 <p>
      <%= f.label :status %><br />
      <%= f.text_area :status %>
 </p>
 <p>
      <%= f.submit "Update the task" %>
 </p>
<% end %>

todolist/app/views/tasks/index.html.erb
<h1>TODO WEB APP</h1>
<% @task.each do |item| %>
 <%= link_to item.name,item %><br><br>
 <%=  item.status %>
   <p>
      <%= link_to "Edit", edit_task_path(item) %> |
      <%= link_to "Mark as Complete",task_mark_path(item) %> |
      <%= link_to "Delete", item, :confirm =>"Are you sure?", :method => :delete %>
   </p>
<hr/>
<% end %>
<p><%= link_to "Add a New Task", new_task_path %></p>

todolist/app/views/tasks/new.html.erb
<h1>Add a New Task</h1>

<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
       <h2> Errors:</h2>
   <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %>
       <% end %>
   </ul>
<% end %>
 <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
 </p>
 <p>
      <%= f.label :status %><br />
      <%= f.text_area :status %>
 </p>
 <p>
      <%= f.submit "Add a New Task" %>
 </p>
<% end %>

todolist/app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p><%= @task.status %></p>
<small><%= @task.created_at %></small>